// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/unittest_multi_nested.proto

package protobuf_unittest;

public final class UnittestMultiNestedProto {
  private UnittestMultiNestedProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OuterOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .protobuf_unittest.Inner one = 1;
    java.util.List<protobuf_unittest.UnittestMultiNestedProto.Inner> 
        getOneList();
    protobuf_unittest.UnittestMultiNestedProto.Inner getOne(int index);
    int getOneCount();
    java.util.List<? extends protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder> 
        getOneOrBuilderList();
    protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder getOneOrBuilder(
        int index);
    
    // repeated .protobuf_unittest.Inner two = 2;
    java.util.List<protobuf_unittest.UnittestMultiNestedProto.Inner> 
        getTwoList();
    protobuf_unittest.UnittestMultiNestedProto.Inner getTwo(int index);
    int getTwoCount();
    java.util.List<? extends protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder> 
        getTwoOrBuilderList();
    protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder getTwoOrBuilder(
        int index);
  }
  public static final class Outer extends
      com.google.protobuf.GeneratedMessage
      implements OuterOrBuilder {
    // Use Outer.newBuilder() to construct.
    private Outer(Builder builder) {
      super(builder);
    }
    private Outer(boolean noInit) {}
    
    private static final Outer defaultInstance;
    public static Outer getDefaultInstance() {
      return defaultInstance;
    }
    
    public Outer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf_unittest.UnittestMultiNestedProto.internal_static_protobuf_unittest_Outer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf_unittest.UnittestMultiNestedProto.internal_static_protobuf_unittest_Outer_fieldAccessorTable;
    }
    
    // repeated .protobuf_unittest.Inner one = 1;
    public static final int ONE_FIELD_NUMBER = 1;
    private java.util.List<protobuf_unittest.UnittestMultiNestedProto.Inner> one_;
    public java.util.List<protobuf_unittest.UnittestMultiNestedProto.Inner> getOneList() {
      return one_;
    }
    public java.util.List<? extends protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder> 
        getOneOrBuilderList() {
      return one_;
    }
    public int getOneCount() {
      return one_.size();
    }
    public protobuf_unittest.UnittestMultiNestedProto.Inner getOne(int index) {
      return one_.get(index);
    }
    public protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder getOneOrBuilder(
        int index) {
      return one_.get(index);
    }
    
    // repeated .protobuf_unittest.Inner two = 2;
    public static final int TWO_FIELD_NUMBER = 2;
    private java.util.List<protobuf_unittest.UnittestMultiNestedProto.Inner> two_;
    public java.util.List<protobuf_unittest.UnittestMultiNestedProto.Inner> getTwoList() {
      return two_;
    }
    public java.util.List<? extends protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder> 
        getTwoOrBuilderList() {
      return two_;
    }
    public int getTwoCount() {
      return two_.size();
    }
    public protobuf_unittest.UnittestMultiNestedProto.Inner getTwo(int index) {
      return two_.get(index);
    }
    public protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder getTwoOrBuilder(
        int index) {
      return two_.get(index);
    }
    
    private void initFields() {
      one_ = java.util.Collections.emptyList();
      two_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getOneCount(); i++) {
        if (!getOne(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getTwoCount(); i++) {
        if (!getTwo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < one_.size(); i++) {
        output.writeMessage(1, one_.get(i));
      }
      for (int i = 0; i < two_.size(); i++) {
        output.writeMessage(2, two_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < one_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, one_.get(i));
      }
      for (int i = 0; i < two_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, two_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protobuf_unittest.UnittestMultiNestedProto.Outer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Outer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Outer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Outer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Outer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Outer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Outer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Outer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Outer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Outer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf_unittest.UnittestMultiNestedProto.Outer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf_unittest.UnittestMultiNestedProto.OuterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf_unittest.UnittestMultiNestedProto.internal_static_protobuf_unittest_Outer_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf_unittest.UnittestMultiNestedProto.internal_static_protobuf_unittest_Outer_fieldAccessorTable;
      }
      
      // Construct using protobuf_unittest.UnittestMultiNestedProto.Outer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOneFieldBuilder();
          getTwoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (oneBuilder_ == null) {
          one_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          oneBuilder_.clear();
        }
        if (twoBuilder_ == null) {
          two_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          twoBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf_unittest.UnittestMultiNestedProto.Outer.getDescriptor();
      }
      
      public protobuf_unittest.UnittestMultiNestedProto.Outer getDefaultInstanceForType() {
        return protobuf_unittest.UnittestMultiNestedProto.Outer.getDefaultInstance();
      }
      
      public protobuf_unittest.UnittestMultiNestedProto.Outer build() {
        protobuf_unittest.UnittestMultiNestedProto.Outer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protobuf_unittest.UnittestMultiNestedProto.Outer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protobuf_unittest.UnittestMultiNestedProto.Outer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protobuf_unittest.UnittestMultiNestedProto.Outer buildPartial() {
        protobuf_unittest.UnittestMultiNestedProto.Outer result = new protobuf_unittest.UnittestMultiNestedProto.Outer(this);
        int from_bitField0_ = bitField0_;
        if (oneBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            one_ = java.util.Collections.unmodifiableList(one_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.one_ = one_;
        } else {
          result.one_ = oneBuilder_.build();
        }
        if (twoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            two_ = java.util.Collections.unmodifiableList(two_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.two_ = two_;
        } else {
          result.two_ = twoBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf_unittest.UnittestMultiNestedProto.Outer) {
          return mergeFrom((protobuf_unittest.UnittestMultiNestedProto.Outer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf_unittest.UnittestMultiNestedProto.Outer other) {
        if (other == protobuf_unittest.UnittestMultiNestedProto.Outer.getDefaultInstance()) return this;
        if (oneBuilder_ == null) {
          if (!other.one_.isEmpty()) {
            if (one_.isEmpty()) {
              one_ = other.one_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOneIsMutable();
              one_.addAll(other.one_);
            }
            onChanged();
          }
        } else {
          if (!other.one_.isEmpty()) {
            if (oneBuilder_.isEmpty()) {
              oneBuilder_.dispose();
              oneBuilder_ = null;
              one_ = other.one_;
              bitField0_ = (bitField0_ & ~0x00000001);
              oneBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOneFieldBuilder() : null;
            } else {
              oneBuilder_.addAllMessages(other.one_);
            }
          }
        }
        if (twoBuilder_ == null) {
          if (!other.two_.isEmpty()) {
            if (two_.isEmpty()) {
              two_ = other.two_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTwoIsMutable();
              two_.addAll(other.two_);
            }
            onChanged();
          }
        } else {
          if (!other.two_.isEmpty()) {
            if (twoBuilder_.isEmpty()) {
              twoBuilder_.dispose();
              twoBuilder_ = null;
              two_ = other.two_;
              bitField0_ = (bitField0_ & ~0x00000002);
              twoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTwoFieldBuilder() : null;
            } else {
              twoBuilder_.addAllMessages(other.two_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getOneCount(); i++) {
          if (!getOne(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getTwoCount(); i++) {
          if (!getTwo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              protobuf_unittest.UnittestMultiNestedProto.Inner.Builder subBuilder = protobuf_unittest.UnittestMultiNestedProto.Inner.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOne(subBuilder.buildPartial());
              break;
            }
            case 18: {
              protobuf_unittest.UnittestMultiNestedProto.Inner.Builder subBuilder = protobuf_unittest.UnittestMultiNestedProto.Inner.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTwo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .protobuf_unittest.Inner one = 1;
      private java.util.List<protobuf_unittest.UnittestMultiNestedProto.Inner> one_ =
        java.util.Collections.emptyList();
      private void ensureOneIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          one_ = new java.util.ArrayList<protobuf_unittest.UnittestMultiNestedProto.Inner>(one_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf_unittest.UnittestMultiNestedProto.Inner, protobuf_unittest.UnittestMultiNestedProto.Inner.Builder, protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder> oneBuilder_;
      
      public java.util.List<protobuf_unittest.UnittestMultiNestedProto.Inner> getOneList() {
        if (oneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(one_);
        } else {
          return oneBuilder_.getMessageList();
        }
      }
      public int getOneCount() {
        if (oneBuilder_ == null) {
          return one_.size();
        } else {
          return oneBuilder_.getCount();
        }
      }
      public protobuf_unittest.UnittestMultiNestedProto.Inner getOne(int index) {
        if (oneBuilder_ == null) {
          return one_.get(index);
        } else {
          return oneBuilder_.getMessage(index);
        }
      }
      public Builder setOne(
          int index, protobuf_unittest.UnittestMultiNestedProto.Inner value) {
        if (oneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOneIsMutable();
          one_.set(index, value);
          onChanged();
        } else {
          oneBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setOne(
          int index, protobuf_unittest.UnittestMultiNestedProto.Inner.Builder builderForValue) {
        if (oneBuilder_ == null) {
          ensureOneIsMutable();
          one_.set(index, builderForValue.build());
          onChanged();
        } else {
          oneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addOne(protobuf_unittest.UnittestMultiNestedProto.Inner value) {
        if (oneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOneIsMutable();
          one_.add(value);
          onChanged();
        } else {
          oneBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addOne(
          int index, protobuf_unittest.UnittestMultiNestedProto.Inner value) {
        if (oneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOneIsMutable();
          one_.add(index, value);
          onChanged();
        } else {
          oneBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addOne(
          protobuf_unittest.UnittestMultiNestedProto.Inner.Builder builderForValue) {
        if (oneBuilder_ == null) {
          ensureOneIsMutable();
          one_.add(builderForValue.build());
          onChanged();
        } else {
          oneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addOne(
          int index, protobuf_unittest.UnittestMultiNestedProto.Inner.Builder builderForValue) {
        if (oneBuilder_ == null) {
          ensureOneIsMutable();
          one_.add(index, builderForValue.build());
          onChanged();
        } else {
          oneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllOne(
          java.lang.Iterable<? extends protobuf_unittest.UnittestMultiNestedProto.Inner> values) {
        if (oneBuilder_ == null) {
          ensureOneIsMutable();
          super.addAll(values, one_);
          onChanged();
        } else {
          oneBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearOne() {
        if (oneBuilder_ == null) {
          one_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          oneBuilder_.clear();
        }
        return this;
      }
      public Builder removeOne(int index) {
        if (oneBuilder_ == null) {
          ensureOneIsMutable();
          one_.remove(index);
          onChanged();
        } else {
          oneBuilder_.remove(index);
        }
        return this;
      }
      public protobuf_unittest.UnittestMultiNestedProto.Inner.Builder getOneBuilder(
          int index) {
        return getOneFieldBuilder().getBuilder(index);
      }
      public protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder getOneOrBuilder(
          int index) {
        if (oneBuilder_ == null) {
          return one_.get(index);  } else {
          return oneBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder> 
           getOneOrBuilderList() {
        if (oneBuilder_ != null) {
          return oneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(one_);
        }
      }
      public protobuf_unittest.UnittestMultiNestedProto.Inner.Builder addOneBuilder() {
        return getOneFieldBuilder().addBuilder(
            protobuf_unittest.UnittestMultiNestedProto.Inner.getDefaultInstance());
      }
      public protobuf_unittest.UnittestMultiNestedProto.Inner.Builder addOneBuilder(
          int index) {
        return getOneFieldBuilder().addBuilder(
            index, protobuf_unittest.UnittestMultiNestedProto.Inner.getDefaultInstance());
      }
      public java.util.List<protobuf_unittest.UnittestMultiNestedProto.Inner.Builder> 
           getOneBuilderList() {
        return getOneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf_unittest.UnittestMultiNestedProto.Inner, protobuf_unittest.UnittestMultiNestedProto.Inner.Builder, protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder> 
          getOneFieldBuilder() {
        if (oneBuilder_ == null) {
          oneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf_unittest.UnittestMultiNestedProto.Inner, protobuf_unittest.UnittestMultiNestedProto.Inner.Builder, protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder>(
                  one_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          one_ = null;
        }
        return oneBuilder_;
      }
      
      // repeated .protobuf_unittest.Inner two = 2;
      private java.util.List<protobuf_unittest.UnittestMultiNestedProto.Inner> two_ =
        java.util.Collections.emptyList();
      private void ensureTwoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          two_ = new java.util.ArrayList<protobuf_unittest.UnittestMultiNestedProto.Inner>(two_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf_unittest.UnittestMultiNestedProto.Inner, protobuf_unittest.UnittestMultiNestedProto.Inner.Builder, protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder> twoBuilder_;
      
      public java.util.List<protobuf_unittest.UnittestMultiNestedProto.Inner> getTwoList() {
        if (twoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(two_);
        } else {
          return twoBuilder_.getMessageList();
        }
      }
      public int getTwoCount() {
        if (twoBuilder_ == null) {
          return two_.size();
        } else {
          return twoBuilder_.getCount();
        }
      }
      public protobuf_unittest.UnittestMultiNestedProto.Inner getTwo(int index) {
        if (twoBuilder_ == null) {
          return two_.get(index);
        } else {
          return twoBuilder_.getMessage(index);
        }
      }
      public Builder setTwo(
          int index, protobuf_unittest.UnittestMultiNestedProto.Inner value) {
        if (twoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTwoIsMutable();
          two_.set(index, value);
          onChanged();
        } else {
          twoBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTwo(
          int index, protobuf_unittest.UnittestMultiNestedProto.Inner.Builder builderForValue) {
        if (twoBuilder_ == null) {
          ensureTwoIsMutable();
          two_.set(index, builderForValue.build());
          onChanged();
        } else {
          twoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTwo(protobuf_unittest.UnittestMultiNestedProto.Inner value) {
        if (twoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTwoIsMutable();
          two_.add(value);
          onChanged();
        } else {
          twoBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTwo(
          int index, protobuf_unittest.UnittestMultiNestedProto.Inner value) {
        if (twoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTwoIsMutable();
          two_.add(index, value);
          onChanged();
        } else {
          twoBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTwo(
          protobuf_unittest.UnittestMultiNestedProto.Inner.Builder builderForValue) {
        if (twoBuilder_ == null) {
          ensureTwoIsMutable();
          two_.add(builderForValue.build());
          onChanged();
        } else {
          twoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTwo(
          int index, protobuf_unittest.UnittestMultiNestedProto.Inner.Builder builderForValue) {
        if (twoBuilder_ == null) {
          ensureTwoIsMutable();
          two_.add(index, builderForValue.build());
          onChanged();
        } else {
          twoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTwo(
          java.lang.Iterable<? extends protobuf_unittest.UnittestMultiNestedProto.Inner> values) {
        if (twoBuilder_ == null) {
          ensureTwoIsMutable();
          super.addAll(values, two_);
          onChanged();
        } else {
          twoBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTwo() {
        if (twoBuilder_ == null) {
          two_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          twoBuilder_.clear();
        }
        return this;
      }
      public Builder removeTwo(int index) {
        if (twoBuilder_ == null) {
          ensureTwoIsMutable();
          two_.remove(index);
          onChanged();
        } else {
          twoBuilder_.remove(index);
        }
        return this;
      }
      public protobuf_unittest.UnittestMultiNestedProto.Inner.Builder getTwoBuilder(
          int index) {
        return getTwoFieldBuilder().getBuilder(index);
      }
      public protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder getTwoOrBuilder(
          int index) {
        if (twoBuilder_ == null) {
          return two_.get(index);  } else {
          return twoBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder> 
           getTwoOrBuilderList() {
        if (twoBuilder_ != null) {
          return twoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(two_);
        }
      }
      public protobuf_unittest.UnittestMultiNestedProto.Inner.Builder addTwoBuilder() {
        return getTwoFieldBuilder().addBuilder(
            protobuf_unittest.UnittestMultiNestedProto.Inner.getDefaultInstance());
      }
      public protobuf_unittest.UnittestMultiNestedProto.Inner.Builder addTwoBuilder(
          int index) {
        return getTwoFieldBuilder().addBuilder(
            index, protobuf_unittest.UnittestMultiNestedProto.Inner.getDefaultInstance());
      }
      public java.util.List<protobuf_unittest.UnittestMultiNestedProto.Inner.Builder> 
           getTwoBuilderList() {
        return getTwoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf_unittest.UnittestMultiNestedProto.Inner, protobuf_unittest.UnittestMultiNestedProto.Inner.Builder, protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder> 
          getTwoFieldBuilder() {
        if (twoBuilder_ == null) {
          twoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf_unittest.UnittestMultiNestedProto.Inner, protobuf_unittest.UnittestMultiNestedProto.Inner.Builder, protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder>(
                  two_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          two_ = null;
        }
        return twoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf_unittest.Outer)
    }
    
    static {
      defaultInstance = new Outer(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf_unittest.Outer)
  }
  
  public interface InnerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .protobuf_unittest.Holder data1 = 1;
    java.util.List<protobuf_unittest.UnittestMultiNestedProto.Holder> 
        getData1List();
    protobuf_unittest.UnittestMultiNestedProto.Holder getData1(int index);
    int getData1Count();
    java.util.List<? extends protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder> 
        getData1OrBuilderList();
    protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder getData1OrBuilder(
        int index);
    
    // repeated .protobuf_unittest.Holder data2 = 2;
    java.util.List<protobuf_unittest.UnittestMultiNestedProto.Holder> 
        getData2List();
    protobuf_unittest.UnittestMultiNestedProto.Holder getData2(int index);
    int getData2Count();
    java.util.List<? extends protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder> 
        getData2OrBuilderList();
    protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder getData2OrBuilder(
        int index);
  }
  public static final class Inner extends
      com.google.protobuf.GeneratedMessage
      implements InnerOrBuilder {
    // Use Inner.newBuilder() to construct.
    private Inner(Builder builder) {
      super(builder);
    }
    private Inner(boolean noInit) {}
    
    private static final Inner defaultInstance;
    public static Inner getDefaultInstance() {
      return defaultInstance;
    }
    
    public Inner getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf_unittest.UnittestMultiNestedProto.internal_static_protobuf_unittest_Inner_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf_unittest.UnittestMultiNestedProto.internal_static_protobuf_unittest_Inner_fieldAccessorTable;
    }
    
    // repeated .protobuf_unittest.Holder data1 = 1;
    public static final int DATA1_FIELD_NUMBER = 1;
    private java.util.List<protobuf_unittest.UnittestMultiNestedProto.Holder> data1_;
    public java.util.List<protobuf_unittest.UnittestMultiNestedProto.Holder> getData1List() {
      return data1_;
    }
    public java.util.List<? extends protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder> 
        getData1OrBuilderList() {
      return data1_;
    }
    public int getData1Count() {
      return data1_.size();
    }
    public protobuf_unittest.UnittestMultiNestedProto.Holder getData1(int index) {
      return data1_.get(index);
    }
    public protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder getData1OrBuilder(
        int index) {
      return data1_.get(index);
    }
    
    // repeated .protobuf_unittest.Holder data2 = 2;
    public static final int DATA2_FIELD_NUMBER = 2;
    private java.util.List<protobuf_unittest.UnittestMultiNestedProto.Holder> data2_;
    public java.util.List<protobuf_unittest.UnittestMultiNestedProto.Holder> getData2List() {
      return data2_;
    }
    public java.util.List<? extends protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder> 
        getData2OrBuilderList() {
      return data2_;
    }
    public int getData2Count() {
      return data2_.size();
    }
    public protobuf_unittest.UnittestMultiNestedProto.Holder getData2(int index) {
      return data2_.get(index);
    }
    public protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder getData2OrBuilder(
        int index) {
      return data2_.get(index);
    }
    
    private void initFields() {
      data1_ = java.util.Collections.emptyList();
      data2_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getData1Count(); i++) {
        if (!getData1(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getData2Count(); i++) {
        if (!getData2(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < data1_.size(); i++) {
        output.writeMessage(1, data1_.get(i));
      }
      for (int i = 0; i < data2_.size(); i++) {
        output.writeMessage(2, data2_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < data1_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data1_.get(i));
      }
      for (int i = 0; i < data2_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, data2_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protobuf_unittest.UnittestMultiNestedProto.Inner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Inner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Inner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Inner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Inner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Inner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Inner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Inner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Inner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Inner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf_unittest.UnittestMultiNestedProto.Inner prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf_unittest.UnittestMultiNestedProto.InnerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf_unittest.UnittestMultiNestedProto.internal_static_protobuf_unittest_Inner_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf_unittest.UnittestMultiNestedProto.internal_static_protobuf_unittest_Inner_fieldAccessorTable;
      }
      
      // Construct using protobuf_unittest.UnittestMultiNestedProto.Inner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getData1FieldBuilder();
          getData2FieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (data1Builder_ == null) {
          data1_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          data1Builder_.clear();
        }
        if (data2Builder_ == null) {
          data2_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          data2Builder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf_unittest.UnittestMultiNestedProto.Inner.getDescriptor();
      }
      
      public protobuf_unittest.UnittestMultiNestedProto.Inner getDefaultInstanceForType() {
        return protobuf_unittest.UnittestMultiNestedProto.Inner.getDefaultInstance();
      }
      
      public protobuf_unittest.UnittestMultiNestedProto.Inner build() {
        protobuf_unittest.UnittestMultiNestedProto.Inner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protobuf_unittest.UnittestMultiNestedProto.Inner buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protobuf_unittest.UnittestMultiNestedProto.Inner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protobuf_unittest.UnittestMultiNestedProto.Inner buildPartial() {
        protobuf_unittest.UnittestMultiNestedProto.Inner result = new protobuf_unittest.UnittestMultiNestedProto.Inner(this);
        int from_bitField0_ = bitField0_;
        if (data1Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            data1_ = java.util.Collections.unmodifiableList(data1_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data1_ = data1_;
        } else {
          result.data1_ = data1Builder_.build();
        }
        if (data2Builder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            data2_ = java.util.Collections.unmodifiableList(data2_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.data2_ = data2_;
        } else {
          result.data2_ = data2Builder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf_unittest.UnittestMultiNestedProto.Inner) {
          return mergeFrom((protobuf_unittest.UnittestMultiNestedProto.Inner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf_unittest.UnittestMultiNestedProto.Inner other) {
        if (other == protobuf_unittest.UnittestMultiNestedProto.Inner.getDefaultInstance()) return this;
        if (data1Builder_ == null) {
          if (!other.data1_.isEmpty()) {
            if (data1_.isEmpty()) {
              data1_ = other.data1_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureData1IsMutable();
              data1_.addAll(other.data1_);
            }
            onChanged();
          }
        } else {
          if (!other.data1_.isEmpty()) {
            if (data1Builder_.isEmpty()) {
              data1Builder_.dispose();
              data1Builder_ = null;
              data1_ = other.data1_;
              bitField0_ = (bitField0_ & ~0x00000001);
              data1Builder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getData1FieldBuilder() : null;
            } else {
              data1Builder_.addAllMessages(other.data1_);
            }
          }
        }
        if (data2Builder_ == null) {
          if (!other.data2_.isEmpty()) {
            if (data2_.isEmpty()) {
              data2_ = other.data2_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureData2IsMutable();
              data2_.addAll(other.data2_);
            }
            onChanged();
          }
        } else {
          if (!other.data2_.isEmpty()) {
            if (data2Builder_.isEmpty()) {
              data2Builder_.dispose();
              data2Builder_ = null;
              data2_ = other.data2_;
              bitField0_ = (bitField0_ & ~0x00000002);
              data2Builder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getData2FieldBuilder() : null;
            } else {
              data2Builder_.addAllMessages(other.data2_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getData1Count(); i++) {
          if (!getData1(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getData2Count(); i++) {
          if (!getData2(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              protobuf_unittest.UnittestMultiNestedProto.Holder.Builder subBuilder = protobuf_unittest.UnittestMultiNestedProto.Holder.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addData1(subBuilder.buildPartial());
              break;
            }
            case 18: {
              protobuf_unittest.UnittestMultiNestedProto.Holder.Builder subBuilder = protobuf_unittest.UnittestMultiNestedProto.Holder.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addData2(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .protobuf_unittest.Holder data1 = 1;
      private java.util.List<protobuf_unittest.UnittestMultiNestedProto.Holder> data1_ =
        java.util.Collections.emptyList();
      private void ensureData1IsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data1_ = new java.util.ArrayList<protobuf_unittest.UnittestMultiNestedProto.Holder>(data1_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf_unittest.UnittestMultiNestedProto.Holder, protobuf_unittest.UnittestMultiNestedProto.Holder.Builder, protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder> data1Builder_;
      
      public java.util.List<protobuf_unittest.UnittestMultiNestedProto.Holder> getData1List() {
        if (data1Builder_ == null) {
          return java.util.Collections.unmodifiableList(data1_);
        } else {
          return data1Builder_.getMessageList();
        }
      }
      public int getData1Count() {
        if (data1Builder_ == null) {
          return data1_.size();
        } else {
          return data1Builder_.getCount();
        }
      }
      public protobuf_unittest.UnittestMultiNestedProto.Holder getData1(int index) {
        if (data1Builder_ == null) {
          return data1_.get(index);
        } else {
          return data1Builder_.getMessage(index);
        }
      }
      public Builder setData1(
          int index, protobuf_unittest.UnittestMultiNestedProto.Holder value) {
        if (data1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureData1IsMutable();
          data1_.set(index, value);
          onChanged();
        } else {
          data1Builder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setData1(
          int index, protobuf_unittest.UnittestMultiNestedProto.Holder.Builder builderForValue) {
        if (data1Builder_ == null) {
          ensureData1IsMutable();
          data1_.set(index, builderForValue.build());
          onChanged();
        } else {
          data1Builder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addData1(protobuf_unittest.UnittestMultiNestedProto.Holder value) {
        if (data1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureData1IsMutable();
          data1_.add(value);
          onChanged();
        } else {
          data1Builder_.addMessage(value);
        }
        return this;
      }
      public Builder addData1(
          int index, protobuf_unittest.UnittestMultiNestedProto.Holder value) {
        if (data1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureData1IsMutable();
          data1_.add(index, value);
          onChanged();
        } else {
          data1Builder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addData1(
          protobuf_unittest.UnittestMultiNestedProto.Holder.Builder builderForValue) {
        if (data1Builder_ == null) {
          ensureData1IsMutable();
          data1_.add(builderForValue.build());
          onChanged();
        } else {
          data1Builder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addData1(
          int index, protobuf_unittest.UnittestMultiNestedProto.Holder.Builder builderForValue) {
        if (data1Builder_ == null) {
          ensureData1IsMutable();
          data1_.add(index, builderForValue.build());
          onChanged();
        } else {
          data1Builder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllData1(
          java.lang.Iterable<? extends protobuf_unittest.UnittestMultiNestedProto.Holder> values) {
        if (data1Builder_ == null) {
          ensureData1IsMutable();
          super.addAll(values, data1_);
          onChanged();
        } else {
          data1Builder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearData1() {
        if (data1Builder_ == null) {
          data1_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          data1Builder_.clear();
        }
        return this;
      }
      public Builder removeData1(int index) {
        if (data1Builder_ == null) {
          ensureData1IsMutable();
          data1_.remove(index);
          onChanged();
        } else {
          data1Builder_.remove(index);
        }
        return this;
      }
      public protobuf_unittest.UnittestMultiNestedProto.Holder.Builder getData1Builder(
          int index) {
        return getData1FieldBuilder().getBuilder(index);
      }
      public protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder getData1OrBuilder(
          int index) {
        if (data1Builder_ == null) {
          return data1_.get(index);  } else {
          return data1Builder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder> 
           getData1OrBuilderList() {
        if (data1Builder_ != null) {
          return data1Builder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data1_);
        }
      }
      public protobuf_unittest.UnittestMultiNestedProto.Holder.Builder addData1Builder() {
        return getData1FieldBuilder().addBuilder(
            protobuf_unittest.UnittestMultiNestedProto.Holder.getDefaultInstance());
      }
      public protobuf_unittest.UnittestMultiNestedProto.Holder.Builder addData1Builder(
          int index) {
        return getData1FieldBuilder().addBuilder(
            index, protobuf_unittest.UnittestMultiNestedProto.Holder.getDefaultInstance());
      }
      public java.util.List<protobuf_unittest.UnittestMultiNestedProto.Holder.Builder> 
           getData1BuilderList() {
        return getData1FieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf_unittest.UnittestMultiNestedProto.Holder, protobuf_unittest.UnittestMultiNestedProto.Holder.Builder, protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder> 
          getData1FieldBuilder() {
        if (data1Builder_ == null) {
          data1Builder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf_unittest.UnittestMultiNestedProto.Holder, protobuf_unittest.UnittestMultiNestedProto.Holder.Builder, protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder>(
                  data1_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          data1_ = null;
        }
        return data1Builder_;
      }
      
      // repeated .protobuf_unittest.Holder data2 = 2;
      private java.util.List<protobuf_unittest.UnittestMultiNestedProto.Holder> data2_ =
        java.util.Collections.emptyList();
      private void ensureData2IsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          data2_ = new java.util.ArrayList<protobuf_unittest.UnittestMultiNestedProto.Holder>(data2_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf_unittest.UnittestMultiNestedProto.Holder, protobuf_unittest.UnittestMultiNestedProto.Holder.Builder, protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder> data2Builder_;
      
      public java.util.List<protobuf_unittest.UnittestMultiNestedProto.Holder> getData2List() {
        if (data2Builder_ == null) {
          return java.util.Collections.unmodifiableList(data2_);
        } else {
          return data2Builder_.getMessageList();
        }
      }
      public int getData2Count() {
        if (data2Builder_ == null) {
          return data2_.size();
        } else {
          return data2Builder_.getCount();
        }
      }
      public protobuf_unittest.UnittestMultiNestedProto.Holder getData2(int index) {
        if (data2Builder_ == null) {
          return data2_.get(index);
        } else {
          return data2Builder_.getMessage(index);
        }
      }
      public Builder setData2(
          int index, protobuf_unittest.UnittestMultiNestedProto.Holder value) {
        if (data2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureData2IsMutable();
          data2_.set(index, value);
          onChanged();
        } else {
          data2Builder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setData2(
          int index, protobuf_unittest.UnittestMultiNestedProto.Holder.Builder builderForValue) {
        if (data2Builder_ == null) {
          ensureData2IsMutable();
          data2_.set(index, builderForValue.build());
          onChanged();
        } else {
          data2Builder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addData2(protobuf_unittest.UnittestMultiNestedProto.Holder value) {
        if (data2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureData2IsMutable();
          data2_.add(value);
          onChanged();
        } else {
          data2Builder_.addMessage(value);
        }
        return this;
      }
      public Builder addData2(
          int index, protobuf_unittest.UnittestMultiNestedProto.Holder value) {
        if (data2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureData2IsMutable();
          data2_.add(index, value);
          onChanged();
        } else {
          data2Builder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addData2(
          protobuf_unittest.UnittestMultiNestedProto.Holder.Builder builderForValue) {
        if (data2Builder_ == null) {
          ensureData2IsMutable();
          data2_.add(builderForValue.build());
          onChanged();
        } else {
          data2Builder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addData2(
          int index, protobuf_unittest.UnittestMultiNestedProto.Holder.Builder builderForValue) {
        if (data2Builder_ == null) {
          ensureData2IsMutable();
          data2_.add(index, builderForValue.build());
          onChanged();
        } else {
          data2Builder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllData2(
          java.lang.Iterable<? extends protobuf_unittest.UnittestMultiNestedProto.Holder> values) {
        if (data2Builder_ == null) {
          ensureData2IsMutable();
          super.addAll(values, data2_);
          onChanged();
        } else {
          data2Builder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearData2() {
        if (data2Builder_ == null) {
          data2_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          data2Builder_.clear();
        }
        return this;
      }
      public Builder removeData2(int index) {
        if (data2Builder_ == null) {
          ensureData2IsMutable();
          data2_.remove(index);
          onChanged();
        } else {
          data2Builder_.remove(index);
        }
        return this;
      }
      public protobuf_unittest.UnittestMultiNestedProto.Holder.Builder getData2Builder(
          int index) {
        return getData2FieldBuilder().getBuilder(index);
      }
      public protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder getData2OrBuilder(
          int index) {
        if (data2Builder_ == null) {
          return data2_.get(index);  } else {
          return data2Builder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder> 
           getData2OrBuilderList() {
        if (data2Builder_ != null) {
          return data2Builder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data2_);
        }
      }
      public protobuf_unittest.UnittestMultiNestedProto.Holder.Builder addData2Builder() {
        return getData2FieldBuilder().addBuilder(
            protobuf_unittest.UnittestMultiNestedProto.Holder.getDefaultInstance());
      }
      public protobuf_unittest.UnittestMultiNestedProto.Holder.Builder addData2Builder(
          int index) {
        return getData2FieldBuilder().addBuilder(
            index, protobuf_unittest.UnittestMultiNestedProto.Holder.getDefaultInstance());
      }
      public java.util.List<protobuf_unittest.UnittestMultiNestedProto.Holder.Builder> 
           getData2BuilderList() {
        return getData2FieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf_unittest.UnittestMultiNestedProto.Holder, protobuf_unittest.UnittestMultiNestedProto.Holder.Builder, protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder> 
          getData2FieldBuilder() {
        if (data2Builder_ == null) {
          data2Builder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf_unittest.UnittestMultiNestedProto.Holder, protobuf_unittest.UnittestMultiNestedProto.Holder.Builder, protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder>(
                  data2_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          data2_ = null;
        }
        return data2Builder_;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf_unittest.Inner)
    }
    
    static {
      defaultInstance = new Inner(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf_unittest.Inner)
  }
  
  public interface HolderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // optional string rev = 2;
    boolean hasRev();
    String getRev();
    
    // optional string data = 3;
    boolean hasData();
    String getData();
  }
  public static final class Holder extends
      com.google.protobuf.GeneratedMessage
      implements HolderOrBuilder {
    // Use Holder.newBuilder() to construct.
    private Holder(Builder builder) {
      super(builder);
    }
    private Holder(boolean noInit) {}
    
    private static final Holder defaultInstance;
    public static Holder getDefaultInstance() {
      return defaultInstance;
    }
    
    public Holder getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf_unittest.UnittestMultiNestedProto.internal_static_protobuf_unittest_Holder_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf_unittest.UnittestMultiNestedProto.internal_static_protobuf_unittest_Holder_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string rev = 2;
    public static final int REV_FIELD_NUMBER = 2;
    private java.lang.Object rev_;
    public boolean hasRev() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getRev() {
      java.lang.Object ref = rev_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          rev_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRevBytes() {
      java.lang.Object ref = rev_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        rev_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private java.lang.Object data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          data_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
      rev_ = "";
      data_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRevBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDataBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRevBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protobuf_unittest.UnittestMultiNestedProto.Holder parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Holder parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Holder parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Holder parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Holder parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Holder parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Holder parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Holder parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Holder parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf_unittest.UnittestMultiNestedProto.Holder parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf_unittest.UnittestMultiNestedProto.Holder prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf_unittest.UnittestMultiNestedProto.HolderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf_unittest.UnittestMultiNestedProto.internal_static_protobuf_unittest_Holder_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf_unittest.UnittestMultiNestedProto.internal_static_protobuf_unittest_Holder_fieldAccessorTable;
      }
      
      // Construct using protobuf_unittest.UnittestMultiNestedProto.Holder.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        rev_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf_unittest.UnittestMultiNestedProto.Holder.getDescriptor();
      }
      
      public protobuf_unittest.UnittestMultiNestedProto.Holder getDefaultInstanceForType() {
        return protobuf_unittest.UnittestMultiNestedProto.Holder.getDefaultInstance();
      }
      
      public protobuf_unittest.UnittestMultiNestedProto.Holder build() {
        protobuf_unittest.UnittestMultiNestedProto.Holder result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protobuf_unittest.UnittestMultiNestedProto.Holder buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protobuf_unittest.UnittestMultiNestedProto.Holder result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protobuf_unittest.UnittestMultiNestedProto.Holder buildPartial() {
        protobuf_unittest.UnittestMultiNestedProto.Holder result = new protobuf_unittest.UnittestMultiNestedProto.Holder(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rev_ = rev_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf_unittest.UnittestMultiNestedProto.Holder) {
          return mergeFrom((protobuf_unittest.UnittestMultiNestedProto.Holder)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf_unittest.UnittestMultiNestedProto.Holder other) {
        if (other == protobuf_unittest.UnittestMultiNestedProto.Holder.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasRev()) {
          setRev(other.getRev());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              rev_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // optional string rev = 2;
      private java.lang.Object rev_ = "";
      public boolean hasRev() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getRev() {
        java.lang.Object ref = rev_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          rev_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRev(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rev_ = value;
        onChanged();
        return this;
      }
      public Builder clearRev() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rev_ = getDefaultInstance().getRev();
        onChanged();
        return this;
      }
      void setRev(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        rev_ = value;
        onChanged();
      }
      
      // optional string data = 3;
      private java.lang.Object data_ = "";
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setData(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      void setData(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf_unittest.Holder)
    }
    
    static {
      defaultInstance = new Holder(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf_unittest.Holder)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_unittest_Outer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_unittest_Outer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_unittest_Inner_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_unittest_Inner_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_unittest_Holder_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_unittest_Holder_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!proto/unittest_multi_nested.proto\022\021pro" +
      "tobuf_unittest\"U\n\005Outer\022%\n\003one\030\001 \003(\0132\030.p" +
      "rotobuf_unittest.Inner\022%\n\003two\030\002 \003(\0132\030.pr" +
      "otobuf_unittest.Inner\"[\n\005Inner\022(\n\005data1\030" +
      "\001 \003(\0132\031.protobuf_unittest.Holder\022(\n\005data" +
      "2\030\002 \003(\0132\031.protobuf_unittest.Holder\"/\n\006Ho" +
      "lder\022\n\n\002id\030\001 \002(\t\022\013\n\003rev\030\002 \001(\t\022\014\n\004data\030\003 " +
      "\001(\tB\034B\030UnittestMultiNestedProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_unittest_Outer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_unittest_Outer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_unittest_Outer_descriptor,
              new java.lang.String[] { "One", "Two", },
              protobuf_unittest.UnittestMultiNestedProto.Outer.class,
              protobuf_unittest.UnittestMultiNestedProto.Outer.Builder.class);
          internal_static_protobuf_unittest_Inner_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_unittest_Inner_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_unittest_Inner_descriptor,
              new java.lang.String[] { "Data1", "Data2", },
              protobuf_unittest.UnittestMultiNestedProto.Inner.class,
              protobuf_unittest.UnittestMultiNestedProto.Inner.Builder.class);
          internal_static_protobuf_unittest_Holder_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protobuf_unittest_Holder_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_unittest_Holder_descriptor,
              new java.lang.String[] { "Id", "Rev", "Data", },
              protobuf_unittest.UnittestMultiNestedProto.Holder.class,
              protobuf_unittest.UnittestMultiNestedProto.Holder.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
